spring.application.name=backend
server.port=8080
# Configuración de AWS Cognito (Debes reemplazar los valores con los de tu cuenta AWS)
# Esto valida automáticamente el 'issuer' (quién emite el token) y la firma digital
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cognito-idp.us-east-1.amazonaws.com/us-east-1_KbBbu5sFd
# Reemplazarás "TU_ENDPOINT_AQUI" cuando AWS termine de crear la base de datos
spring.datasource.url=jdbc:mysql://pedidos360-db.cb30y1inz0bh.us-east-1.rds.amazonaws.com:3306/pedidos360
spring.datasource.username=admin
spring.datasource.password=pedidos360_pass

# Esto le dice a Spring que genere o actualice las tablas (como 'Pedido') automáticamente
spring.jpa.hibernate.ddl-auto=update
# Le decimos explícitamente que use el dialecto de MySQL para evitar el error que te salió
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect