spring.application.name=backend
server.port=8080
# Configuración de AWS Cognito (Debes reemplazar los valores con los de tu cuenta AWS)
# Esto valida automáticamente el 'issuer' (quién emite el token) y la firma digital
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cognito-idp.us-east-1.amazonaws.com/TU_USER_POOL_ID
# Conexión a la Base de Datos Cloud (AWS RDS)
spring.datasource.url=jdbc:mysql://TU_ENDPOINT_DE_AWS_RDS:3306/pedidos360?createDatabaseIfNotExist=true
spring.datasource.username=admin
spring.datasource.password=tu_contraseña_de_aws
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate: Actualiza la estructura de la base de datos automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true