spring.application.name=backend
server.port=8080
# Configuración de AWS Cognito (Debes reemplazar los valores con los de tu cuenta AWS)
# Esto valida automáticamente el 'issuer' (quién emite el token) y la firma digital
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cognito-idp.us-east-1.amazonaws.com/TU_USER_POOL_ID